version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "tailwindcss"
      - dependency-name: "autoprefixer"
      - dependency-name: "@types/node"
